In [2]:
import pandas as pd 
df1=pd.read_csv("C:\\Users\Rahul\\Downloads\\df1_c.csv")
df2=pd.read_csv("C:\\Users\\Rahul\\Downloads\\df2_c.csv")
merged_df=pd.merge(df1,df2,on='customer_id')

In [3]:
merged_df.duplicated().sum()
merged_df.drop_duplicates()

,customer_id,name,email,phone,address,registration_date,loyalty_status,transaction_id,amount,transaction_date,product_category,payment_method,store_location
0,1,Michelle Kidd,vayala@example.net,NaN,"USNS Santiago, FPO AE 80872",2025-01-25,Gold,8,2652.57,2025-04-19 14:46:00,Home,Credit Card,New York
1,4,Kimberly Price,jessicaknight@example.com,001-947-633-4224x07930,"1631 Alexis Meadows, Lake Amanda, CA 75179",2024-12-08,Gold,427,1787.09,2025-04-28 04:34:07,Beauty,PayPal,Chicago
2,5,Matthew Phillips,qwilliams@example.com,001-869-650-5682x8385,"2274 Williams Heights Suite 895, Andersonhaven...",2024-02-03,Gold,452,1983.52,2025-02-03 14:59:13,Sports,PayPal,Online
3,7,Louis Miller,patriciaelliott@example.org,001-418-931-4146x588,"02590 Marshall Well, Sheppardland, CT 88067",2024-09-30,Gold,470,3241.66,2025-05-15 15:17:05,Electronics,PayPal,Los Angeles
4,7,Louis Miller,patriciaelliott@example.org,001-418-931-4146x588,"02590 Marshall Well, Sheppardland, CT 88067",2024-09-30,Gold,857,697.57,2025-06-13 12:03:42,Beauty,Debit Card,Chicago
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,Deanna Johnson,ycook@example.org,+1-639-853-2802,"601 Contreras Forges, Michaelfurt, KY 30733",2023-11-01,Silver,532,759.38,2025-03-14 16:56:22,Home,PayPal,New York
996,995,Deanna Johnson,ycook@example.org,+1-639-853-2802,"601 Contreras Forges, Michaelfurt, KY 30733",2023-11-01,Silver,617,821.18,2025-01-23 07:39:19,Electronics,Debit Card,Miami
997,997,Jodi Simpson,eric24@example.org,+1-408-681-5204x264,"2876 Tucker Road Suite 947, North Tommyborough...",2024-04-18,Bronze,45,480.64,2025-01-06 08:27:59,Home,Credit Card,Los Angeles
998,998,Crystal Brown,pshaffer@example.net,(962)521-7928,"095 Janice Forest Suite 570, Boltonmouth, DE 7...",2024-08-30,Bronze,304,73.71,2025-01-27 05:33:22,Home,Debit Card,Chicago
999,998,Crystal Brown,pshaffer@example.net,(962)521-7928,"095 Janice Forest Suite 570, Boltonmouth, DE 7...",2024-08-30,Bronze,886,NaN,2025-03-16 15:42:17,Beauty,Debit Card,Online

In [4]:
def fill_nulls(merged_df):
    for col in merged_df.columns:
        if col=='amount':
            merged_df[col]=merged_df[col].fillna(merged_df['amount'].mean())
        elif merged_df[col].dtype=='object':
            merged_df[col]=merged_df[col].fillna(f'unknown_{col}')
        else :
            merged_df[col]=merged_df[col].fillna(0) 
    return merged_df

cleaned_data=fill_nulls(merged_df)

cleaned_data

,customer_id,name,email,phone,address,registration_date,loyalty_status,transaction_id,amount,transaction_date,product_category,payment_method,store_location
0,1,Michelle Kidd,vayala@example.net,unknown_phone,"USNS Santiago, FPO AE 80872",2025-01-25,Gold,8,2652.570000,2025-04-19 14:46:00,Home,Credit Card,New York
1,4,Kimberly Price,jessicaknight@example.com,001-947-633-4224x07930,"1631 Alexis Meadows, Lake Amanda, CA 75179",2024-12-08,Gold,427,1787.090000,2025-04-28 04:34:07,Beauty,PayPal,Chicago
2,5,Matthew Phillips,qwilliams@example.com,001-869-650-5682x8385,"2274 Williams Heights Suite 895, Andersonhaven...",2024-02-03,Gold,452,1983.520000,2025-02-03 14:59:13,Sports,PayPal,Online
3,7,Louis Miller,patriciaelliott@example.org,001-418-931-4146x588,"02590 Marshall Well, Sheppardland, CT 88067",2024-09-30,Gold,470,3241.660000,2025-05-15 15:17:05,Electronics,PayPal,Los Angeles
4,7,Louis Miller,patriciaelliott@example.org,001-418-931-4146x588,"02590 Marshall Well, Sheppardland, CT 88067",2024-09-30,Gold,857,697.570000,2025-06-13 12:03:42,Beauty,Debit Card,Chicago
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,Deanna Johnson,ycook@example.org,+1-639-853-2802,"601 Contreras Forges, Michaelfurt, KY 30733",2023-11-01,Silver,532,759.380000,2025-03-14 16:56:22,Home,PayPal,New York
996,995,Deanna Johnson,ycook@example.org,+1-639-853-2802,"601 Contreras Forges, Michaelfurt, KY 30733",2023-11-01,Silver,617,821.180000,2025-01-23 07:39:19,Electronics,Debit Card,Miami
997,997,Jodi Simpson,eric24@example.org,+1-408-681-5204x264,"2876 Tucker Road Suite 947, North Tommyborough...",2024-04-18,Bronze,45,480.640000,2025-01-06 08:27:59,Home,Credit Card,Los Angeles
998,998,Crystal Brown,pshaffer@example.net,(962)521-7928,"095 Janice Forest Suite 570, Boltonmouth, DE 7...",2024-08-30,Bronze,304,73.710000,2025-01-27 05:33:22,Home,Debit Card,Chicago
999,998,Crystal Brown,pshaffer@example.net,(962)521-7928,"095 Janice Forest Suite 570, Boltonmouth, DE 7...",2024-08-30,Bronze,886,2532.550126,2025-03-16 15:42:17,Beauty,Debit Card,Online